# Microsoft Entra External Identities Tenants
# Status: Tested

# Tenant operations showcased
# - newTenant: Creates a new tenant
#   - Async process so has two steps, the send and an update which includes
#     some error messages
# - getTenant: Retrieves information about a specific tenant
# - updateTenant: Updates the properties of a specific tenant
# - listTenantrg: Lists all tenants within a specific resource group
# - deleteTenant: Deletes a specific tenant

# Prerequisites
# - Subscription
# - Contributor or narrower role permission to operate on these resource kinds
# - An application registration is required with key configuration
#   - user_impersonation for the azure management plane APIs
#   - allow public client logins

# Generic functionality required
# - login: Use the device login flow to act as yourself on Azure
# - newrg: Creates a new resource group
#     - It's good to keep stuff in a single RG for testing purposes

# Developer Recommendations
# - Using the extension humao.rest-client enables transpiling these requests
#   into different languages
# - Do make sure to check out the docs for the extension to see if other
#   functionality is useful to you


# Login to get an auth token
# @name loginCode
POST https://login.microsoftonline.com/{{tenantId}}/oauth2/v2.0/devicecode
Content-Type: application/x-www-form-urlencoded

scope=https%3A%2F%2Fmanagement.azure.com%2Fuser_impersonation
&client_id={{clientId}}

###

# Use the device login from the above's response and login on browser 
# @name loginGetToken
POST https://login.microsoftonline.com/{{tenantId}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

grant_type=urn:ietf:params:oauth:grant-type:device_code
&client_id={{clientId}}
&device_code={{loginCode.response.body.device_code}}

###

@authToken={{loginGetToken.response.body.access_token}}
# Create resource group if not exists
# @name newrg
PUT https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}?api-version=2021-04-01
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "location": "centralus"
}

###

# Create tenant
# The domain should be unique and not already in use, ending in onmicrosoft.com!
# You need to run the next script for checking the async logs to see if 
# this actually passed validation of domain name etc, otherwise you'll just see 
# a broken tenant forever in the portal with no obvious issues beyond no guid
# https://learn.microsoft.com/en-us/rest/api/activedirectory/ciam-tenants/create?view=rest-activedirectory-2023-05-17-preview&tabs=HTTP
# @name newTenant
PUT https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.AzureActiveDirectory/ciamDirectories/{{newTenantName}}?api-version=2023-05-17-preview
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "location": "unitedstates",
  "sku": {
    "name": "Standard",
    "tier": "A0"
  },
  "properties": {
    "createTenantProperties": {
      "displayName": "Testing CIAM processes",
      "countryCode": "US"
    }
  }
}

###
@newTenantId = {{newTenant.response.body.id}}

# Check new tenant provisioning status
# You may need to run this multiple times to check
# @name checkTenantProvisioningStatus
GET {{newTenant.response.headers.Azure-AsyncOperation}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

# Get tenant
# Note the creation of the tenant can take a little while!
# https://learn.microsoft.com/en-us/rest/api/activedirectory/ciam-tenants/get?view=rest-activedirectory-2023-05-17-preview&tabs=HTTP
# @name getTenant
GET https://management.azure.com/{{newTenantId}}?api-version=2023-05-17-preview
Authorization: Bearer  {{authToken}}
Content-Type: application/json

###

# Update tenant
# https://learn.microsoft.com/en-us/rest/api/activedirectory/ciam-tenants/update?view=rest-activedirectory-2023-05-17-preview&tabs=HTTP
# @name updateTenant
PATCH https://management.azure.com/{{newTenantId}}?api-version=2023-05-17-preview
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "tags":{
    "purpose":"Testing"
  }
}

###

# List tenants in rg
# NB there is one for listing at the sub level but better to be scoped where possible
# https://learn.microsoft.com/en-us/rest/api/activedirectory/ciam-tenants/list-by-resource-group?view=rest-activedirectory-2023-05-17-preview&tabs=HTTP
# @name listTenantrg
GET https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.AzureActiveDirectory/ciamDirectories?api-version=2023-05-17-preview
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

# Delete tenant
# https://learn.microsoft.com/en-us/rest/api/activedirectory/ciam-tenants/delete?view=rest-activedirectory-2023-05-17-preview&tabs=HTTP
# @name deleteTenant
DELETE https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{{resourceGroupName}}/providers/Microsoft.AzureActiveDirectory/ciamDirectories/{{newTenantId}}?api-version=2023-05-17-preview
Authorization: Bearer {{authToken}}
Content-Type: application/json
###
